import { GraphQLDefinitionsFactory } from "@nestjs/graphql";
import { join } from "path";

const definitionsFactory = new GraphQLDefinitionsFactory();
definitionsFactory.generate({
  typePaths: ["./src/**/*.graphql"],
  path: join(process.cwd(), "src/graphql.schema.ts"),
  outputAs: "class",
  defaultScalarType: "unknown",
  customScalarTypeMapping: {
    JSON: "Record<string,any>",
    EMAIL: "string",
  },
  additionalHeader:
    "// integration of `graphql-scalars` with types generated by Nest",
});
